@host=http://localhost:5260

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName" : "Chidi",
    "lastName" : "Jude",
    "email" : "cjude@qore.inc",
    "password" : "Chidi112"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
    "email" : "cjude@qore.inc",
    "password" : "Chidi112"
}
