@host=http://localhost:5260
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiQ2hpZGkiLCJmYW1pbHlfbmFtZSI6Ikp1ZGUiLCJqdGkiOiJjMDc3ZDg1Yi1iNTczLTRmMDEtOTc5Zi1kZTMxNTIxMTNlZTUiLCJzdWIiOiJhZjM2M2Y5Mi1lYzJlLTRmNTUtOWViYy1kOWVkODZhN2E1MTIiLCJleHAiOjE3MjA4MDI1NjIsImlzcyI6Ik9wZW5EaW5uZXIiLCJhdWQiOiJPcGVuRGlubmVyIn0.z4zpWhLUpcTeCjFsBfYKQ5wo55ZwB8dmqcTep3Zwim8
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName" : "Chidi",
    "lastName" : "Jude",
    "email" : "cjude@qore.inc",
    "password" : "Chidi112"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
    "email" : "cjude@qore.inc",
    "password" : "Chidi112"
}

###

GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer {{token}}

###
@hostId=afda9665-1f48-4886-bc54-3a92d4249fab
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Slim Menu",
    "description" : "Yummy foods",
    "sections": [
        {
            "name": "Swallow",
            "description": "starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}