@host=http://localhost:5260
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiQ2hpZGkiLCJmYW1pbHlfbmFtZSI6Ikp1ZGUiLCJqdGkiOiIxMTYwMTAzNy1hZGVjLTQ4NzItOWJjMy00OTY5OTk3OGUwYTIiLCJzdWIiOiI4NmZmOWE4OC04MDYwLTQ0ZjItYjE3Ni1iMTQyMDAzZWMxZTYiLCJleHAiOjE3MjA4ODA0OTIsImlzcyI6Ik9wZW5EaW5uZXIiLCJhdWQiOiJPcGVuRGlubmVyIn0.svfMZmuxbqtmP59HjiUv_mb0BvDvWQl81uKqKe3netg
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName" : "Chidi",
    "lastName" : "Jude",
    "email" : "anyemail@mail.inc",
    "password" : "Chidi112"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
    "email" : "anyemail@mail.inc",
    "password" : "Chidi112"
}

###

GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer {{token}}

###
@hostId=afda9665-1f48-4886-bc54-3a92d4249fab
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Slim Menu",
    "description" : "Yummy foods",
    "sections": [
        {
            "name": "Swallow",
            "description": "starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}
